esphome:
  name: dinrail-switch-1

bk72xx:
  board: generic-bk7231n-qfn32-tuya

logger:

mdns:

api:
  encryption:
    key: !secret api_secret

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

#preferences:
#  flash_write_interval: 1min

button:
  - platform: restart
    name: Restart
  - platform: template
    name: "Toggle Relay"
    id: soft_button
    on_press:
      switch.toggle: relay

debug:
  update_interval: 30s

text_sensor:
  - platform: debug
    reset_reason:
      name: Reset Reason
  - platform: libretiny
    version:
      name: LibreTiny Version

switch:
  - platform: template
    name: Relay
    id: relay
    turn_on_action:
      - switch.turn_on: on_relay
    turn_off_action:
      - switch.turn_on: off_relay
    optimistic: true
    internal: true
    restore_mode: RESTORE_DEFAULT_ON
  - platform: gpio
    pin:
      number: P24
      inverted: true
    id: off_relay
    name: "OFF Relay"
    restore_mode: ALWAYS_OFF
    internal: True
    interlock: [on_relay]
    on_turn_on:
      - light.turn_off: redled
      - binary_sensor.template.publish:
          id: relaystate
          state: OFF
      - delay: 100ms
      - switch.turn_off: off_relay
  - platform: gpio
    pin:
      number: P26
      inverted: true
    id: on_relay
    name: "ON Relay"
    restore_mode: ALWAYS_OFF
    internal: True
    interlock: [off_relay]
    on_turn_on:
      - light.turn_on: redled
      - binary_sensor.template.publish:
          id: relaystate
          state: ON
      - delay: 100ms
      - switch.turn_off: on_relay

binary_sensor:
  - platform: gpio
    pin: 
      number: P17
      inverted: true
      mode:
        input: true
    name: "Button"
    id: hard_button
    on_press:
      switch.toggle: relay
    internal: true
  - platform: template
    name: Relay State
    id: relaystate

light:
  - platform: binary
    name: "REDLED"
    output: redled_output
    id: redled
    internal: true

output:
  - id: redled_output
    platform: gpio
    pin:
      number: P9
      inverted: true
      mode:
        output: true

sensor:
  - platform: uptime
    name: Uptime
  - platform: bl0942
    uart_id: uart_bus
    current:
      name: BL0942 Current
    voltage:
      name: BL0942 Voltage
    power:
      name: BL0942 Power
      filters:
        multiply: -1
    energy:
      name: BL0942 Energy
    frequency:
      name: BL0942 Frequency
      accuracy_decimals: 2

status_led:
  pin:
    number: P15
    inverted: false

uart:
  id: uart_bus
  tx_pin: TX1
  rx_pin: RX1
  baud_rate: 4800
  stop_bits: 1
