esphome:
  name: esp32-bt-proxy-f3e36c

esp32:
  board: esp32dev
  framework:
    type: arduino

bluetooth_proxy:
  active: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  password: !secret ota_password

api:
  encryption:
    key: !secret api_secret

# Enable logging
logger:

improv_serial:

button:
- platform: safe_mode
  name: Safe Mode Boot
  entity_category: diagnostic