substitutions:
  name: esp32-bluetooth-proxy-d74430
  friendly_name: Bluetooth Proxy d74430
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic-c3.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: C5AXHgA0CGsEMno3jwlD4gbyWmfiTzlARvYa8ADTk2g=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
