substitutions:
  name: esp32-bluetooth-proxy-246d94
  friendly_name: Bluetooth Proxy 246d94
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: VBB/y7Q2rw19dBonLW3gWavzKtnlAPJm6mHhULN5nr4=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
