substitutions:
  name: esp32-bluetooth-proxy-f3e36c
  friendly_name: Bluetooth Proxy f3e36c
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: iYwIxdoTWuoZslJD4+HzoIquoyedGl5V+OAIxl1uqeU=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
