substitutions:
  name: esp32-bluetooth-proxy-f35024
  friendly_name: Bluetooth Proxy f35024 Antenne

packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret api_secret

#logger:
#  level: VERBOSE

ota:
  - platform: esphome
    password: !secret ota_password
