esphome:
  name: tdisplay-s3-amoled-temp
  on_boot:
    priority: -60 
    then:
      - lambda: |-
          // Create chart
          id(my_chart) = lv_chart_create(lv_scr_act());
          lv_obj_set_size(id(my_chart), 450, 120);
          lv_obj_align(id(my_chart), LV_ALIGN_BOTTOM_MID, 0, -10);
          lv_chart_set_type(id(my_chart), LV_CHART_TYPE_LINE);
          lv_chart_set_point_count(id(my_chart), 60);
          
          // Styling
          lv_obj_set_style_bg_opa(id(my_chart), 0, 0);
          lv_obj_set_style_border_width(id(my_chart), 0, 0);
          
          // Series assignment (casting to void* for the globals)
          id(ser_cons) = (void*)lv_chart_add_series(id(my_chart), lv_color_hex(0xFF0000), LV_CHART_AXIS_PRIMARY_Y);
          id(ser_prod) = (void*)lv_chart_add_series(id(my_chart), lv_color_hex(0x00FF00), LV_CHART_AXIS_PRIMARY_Y);
          id(ser_solar) = (void*)lv_chart_add_series(id(my_chart), lv_color_hex(0xFF9900), LV_CHART_AXIS_PRIMARY_Y);
          
          lv_obj_add_flag(id(my_chart), LV_OBJ_FLAG_HIDDEN);

# ... hardware/connectivity (same as before) ...

# --- GLOBALS ---
globals:
  - id: my_chart
    type: lv_obj_t*
    initial_value: 'nullptr'
  - id: ser_cons
    type: void*
    initial_value: 'nullptr'
  - id: ser_prod
    type: void*
    initial_value: 'nullptr'
  - id: ser_solar
    type: void*
    initial_value: 'nullptr'

# --- LVGL UI ---
lvgl:
  log_level: DEBUG
  # THE CRITICAL SECTION
  widgets:
    - chart: # Added colon to make it a dictionary key

  pages:
    - id: page1
      bg_color: 0x000000
      on_focus:
        - lambda: 'if(id(my_chart)) lv_obj_add_flag(id(my_chart), LV_OBJ_FLAG_HIDDEN);'
      widgets:
        - obj: &header_bar
            width: 100%
            height: 30
            # ... header widgets ...

    - id: page2
      bg_color: 0x000000
      on_focus:
        - lambda: 'if(id(my_chart)) lv_obj_clear_flag(id(my_chart), LV_OBJ_FLAG_HIDDEN);'
      # ... page 2 widgets ...

    - id: page3
      bg_color: 0x000000
      on_focus:
        - lambda: 'if(id(my_chart)) lv_obj_clear_flag(id(my_chart), LV_OBJ_FLAG_HIDDEN);'
      # ... page 3 widgets ...

# --- SENSORS ---
sensor:
  - platform: homeassistant
    id: power_prod
    entity_id: sensor.power_produced
    on_value:
      - lambda: 'if(id(my_chart)) lv_chart_set_next_value(id(my_chart), (lv_chart_series_t*)id(ser_prod), x * 1000.0);'
# ... rest of sensors ...