esphome:
  name: t-display-s3-pro-lvgltest
  friendly_name: "T-Display S3 Pro Power Monitor"
  platformio_options:
    build_flags: ["-DLV_USE_CHART=1"]
    board_build.flash_mode: dio
  on_boot:
    priority: 100
    then:
      - switch.turn_on: display_power
      - light.turn_on: { id: display_backlight, brightness: 100% }
      - delay: 1s
      - script.execute: setup_chart

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

external_components:
  - source: github://esphome/esphome@dev
    components: [sy6970]

api:
  encryption:
    key: !secret api_secret

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

psram:
  mode: octal
  speed: 80MHz

logger:

spi:
  clk_pin: 18
  mosi_pin: 17
  miso_pin: 16

i2c:
  id: i2c_bus
  sda: 5
  scl: 6

output:
  - platform: ledc
    pin: 48
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    id: display_backlight

switch:
  - platform: gpio
    pin: 15
    id: display_power
    restore_mode: ALWAYS_ON

display:
  - platform: mipi_spi
    id: my_display
    model: t-display-s3-pro
    rotation: 90

touchscreen:
  - platform: cst226
    id: my_touch
    interrupt_pin: 21
    reset_pin: 13
    display: my_display

font:
  - file: 'fonts/BebasNeue-Regular.ttf'
    id: font_bebas_80
    size: 80
  - file: 'fonts/arial.ttf'
    id: font_arial_20
    size: 20

globals:
  - { id: battery_percent, type: float, initial_value: '0.0' }
  - { id: my_chart, type: lv_obj_t*, initial_value: 'nullptr' }
  - { id: ser_cons, type: lv_chart_series_t*, initial_value: 'nullptr' }
  - { id: ser_prod, type: lv_chart_series_t*, initial_value: 'nullptr' }
  - { id: ser_solar, type: lv_chart_series_t*, initial_value: 'nullptr' }

lvgl:
  touchscreens:
    - touchscreen_id: my_touch
  buffer_size: 25%
  pages:
    - id: page1
      bg_color: 0x000000
      widgets:
        - obj:
            width: 100%
            height: 40
            bg_color: 0x2828FF
            align: TOP_MID
            layout: { type: FLEX, flex_flow: ROW, flex_align_main: SPACE_BETWEEN, flex_align_cross: CENTER }
            pad_left: 10
            pad_right: 10
            widgets:
              - label: { id: time_p1, text: "--:--:--", text_font: font_arial_20 }
              - obj:
                  layout: { type: FLEX, flex_flow: ROW }
                  bg_opa: 0
                  widgets:
                    - label: { id: batt_v_p1, text: "--.-V", text_font: font_arial_20 }
                    - label: { text: " ", text_font: font_arial_20 }
                    - label: { id: batt_pct_p1, text: "--%", text_font: font_arial_20 }
        - obj:
            width: 100%
            height: 180
            align: TOP_MID
            y: 40
            layout: { type: FLEX, flex_flow: COLUMN, flex_align_main: CENTER, flex_align_cross: CENTER }
            bg_opa: 0
            widgets:
              - label: { id: main_pwr_p1, text: "--- W", text_font: font_bebas_80 }

    - id: page2
      bg_color: 0x000000
      widgets:
        - obj:
            width: 100%
            height: 80
            align: CENTER
            layout: { type: FLEX, flex_flow: COLUMN, flex_align_main: CENTER, flex_align_cross: CENTER }
            bg_opa: 0
            widgets:
              - label: { id: main_pwr_p2, text: "--- W", text_font: font_bebas_80 }

    - id: page3
      bg_color: 0x000000
      widgets:
        - obj:
            width: 100%
            height: 80
            align: CENTER
            layout: { type: FLEX, flex_flow: COLUMN, flex_align_main: CENTER, flex_align_cross: CENTER }
            bg_opa: 0
            widgets:
              - label: { id: solar_pwr_p3, text: "--- W", text_font: font_bebas_80 }

script:
  - id: setup_chart
    then:
      - lambda: |-
          if (!id(my_chart)) {
            id(my_chart) = lv_chart_create(id(page2).obj);
            lv_obj_set_size(id(my_chart), 480, 100);
            lv_obj_align(id(my_chart), LV_ALIGN_BOTTOM_MID, 0, 0);
            lv_chart_set_point_count(id(my_chart), 60);
            lv_chart_set_range(id(my_chart), LV_CHART_AXIS_PRIMARY_Y, 0, 5000);
            id(ser_cons)  = lv_chart_add_series(id(my_chart), lv_color_hex(0xFF0000), LV_CHART_AXIS_PRIMARY_Y);
            id(ser_prod)  = lv_chart_add_series(id(my_chart), lv_color_hex(0x00FF00), LV_CHART_AXIS_PRIMARY_Y);
            id(ser_solar) = lv_chart_add_series(id(my_chart), lv_color_hex(0xFF9900), LV_CHART_AXIS_PRIMARY_Y);
          }

sy6970:
  i2c_id: i2c_bus
  update_interval: 30s

time:
  - platform: homeassistant
    id: esptime
    on_time:
      - seconds: /1
        then:
          - lvgl.label.update: { id: time_p1, text: !lambda 'return id(esptime).now().strftime("%H:%M:%S");' }

sensor:
  - platform: sy6970
    battery_voltage:
      id: battery_voltage
      on_value:
        - lambda: |-
            float pct = (x - 3.0f) / 1.2f * 100.0f;
            if (pct < 0) pct = 0;
            if (pct > 100) pct = 100;
            id(battery_percent) = pct;
        - lvgl.label.update: { id: batt_v_p1, text: !lambda 'return str_sprintf("%.2fV", x);' }
        - lvgl.label.update: { id: batt_pct_p1, text: !lambda 'return str_sprintf("%.0f%%", id(battery_percent));' }

  - platform: homeassistant
    id: main_power
    entity_id: sensor.ecotracker_current_power
    on_value:
      - if:
          condition: { lambda: 'return !isnan(x);' }
          then:
            - lvgl.label.update: { id: main_pwr_p1, text: !lambda 'return str_sprintf("%.0f W", x);' }
            - lambda: |-
                lv_color_t c;
                if (x < 0) c = lv_color_hex(0x4FC3F7);
                else if (x <= 500) c = lv_color_hex(0x4CAF50);
                else if (x <= 1000) c = lv_color_hex(0xFF9800);
                else c = lv_color_hex(0xF44336);
                lv_obj_set_style_text_color(id(main_pwr_p1), c, LV_PART_MAIN);
            - lvgl.label.update: { id: main_pwr_p2, text: !lambda 'return str_sprintf("%.0f W", x);' }

  - platform: homeassistant
    id: solar_power
    entity_id: sensor.dds238_2_solar_energy_power
    on_value:
      - lvgl.label.update: { id: solar_pwr_p3, text: !lambda 'return str_sprintf("%.0f W", x);' }

binary_sensor:
  - platform: gpio
    id: button_next_page
    pin: { number: GPIO00, inverted: true, mode: INPUT_PULLUP }
    on_press:
      - lvgl.page.next: