# Lilygo T-Display-S3-Pro
# To flash this to the device:
# With the device plugged in via USB:
#  - install ESPHome:
#       pip install esphome
#  - build and run:
#       esphome run t-display-s3-pro.yaml


esphome:
  name: t-display-s3-pro-energy

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

api:
  encryption:
    key: !secret api_secret

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

psram:
  mode: octal
  speed: 80MHz

logger:

power_supply:
  - id: backlight
    pin: 48
    enable_on_boot: true

spi:
  clk_pin: 18
  mosi_pin: 17

i2c:
  - scl: 6
    sda: 5
    scan: true
    id: i2c_onboard
    frequency: 400kHz

touchscreen:
  - platform: cst226
    interrupt_pin: 21
    reset_pin: 13
    on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.x, touch.y, touch.x_raw, touch.y_raw);

binary_sensor:
  - platform: cst226
    id: cst226_sensor
    on_click:
      - logger.log: Sensor clicked


display:
  - platform: mipi_spi
    model: t-display-s3-pro

sensor:
  - platform: homeassistant
    id: shellypro3em_total_power
    entity_id: sensor.441d6474d608_pro3em_active_power_c
    unit_of_measurement: 'W'
    on_value:
      - lambda: |-
          for (int i = 0; i < 29; i++) {
            id(power_history)[i] = id(power_history)[i + 1];
          }

          float v = x;
          if (v < 0) v = 0;
          if (v > 3000) v = 3000;
          id(power_history)[29] = v;

      - lvgl.bar.update:
          id: power_bar_0
          value: !lambda return id(power_history)[0];
      - lvgl.bar.update:
          id: power_bar_1
          value: !lambda return id(power_history)[1];
      - lvgl.bar.update:
          id: power_bar_2
          value: !lambda return id(power_history)[2];
      - lvgl.bar.update:
          id: power_bar_3
          value: !lambda return id(power_history)[3];
      - lvgl.bar.update:
          id: power_bar_4
          value: !lambda return id(power_history)[4];
      - lvgl.bar.update:
          id: power_bar_5
          value: !lambda return id(power_history)[5];
      - lvgl.bar.update:
          id: power_bar_6
          value: !lambda return id(power_history)[6];
      - lvgl.bar.update:
          id: power_bar_7
          value: !lambda return id(power_history)[7];
      - lvgl.bar.update:
          id: power_bar_8
          value: !lambda return id(power_history)[8];
      - lvgl.bar.update:
          id: power_bar_9
          value: !lambda return id(power_history)[9];
      - lvgl.bar.update:
          id: power_bar_10
          value: !lambda return id(power_history)[10];
      - lvgl.bar.update:
          id: power_bar_11
          value: !lambda return id(power_history)[11];
      - lvgl.bar.update:
          id: power_bar_12
          value: !lambda return id(power_history)[12];
      - lvgl.bar.update:
          id: power_bar_13
          value: !lambda return id(power_history)[13];
      - lvgl.bar.update:
          id: power_bar_14
          value: !lambda return id(power_history)[14];
      - lvgl.bar.update:
          id: power_bar_15
          value: !lambda return id(power_history)[15];
      - lvgl.bar.update:
          id: power_bar_16
          value: !lambda return id(power_history)[16];
      - lvgl.bar.update:
          id: power_bar_17
          value: !lambda return id(power_history)[17];
      - lvgl.bar.update:
          id: power_bar_18
          value: !lambda return id(power_history)[18];
      - lvgl.bar.update:
          id: power_bar_19
          value: !lambda return id(power_history)[19];
      - lvgl.bar.update:
          id: power_bar_20
          value: !lambda return id(power_history)[20];
      - lvgl.bar.update:
          id: power_bar_21
          value: !lambda return id(power_history)[21];
      - lvgl.bar.update:
          id: power_bar_22
          value: !lambda return id(power_history)[22];
      - lvgl.bar.update:
          id: power_bar_23
          value: !lambda return id(power_history)[23];
      - lvgl.bar.update:
          id: power_bar_24
          value: !lambda return id(power_history)[24];
      - lvgl.bar.update:
          id: power_bar_25
          value: !lambda return id(power_history)[25];
      - lvgl.bar.update:
          id: power_bar_26
          value: !lambda return id(power_history)[26];
      - lvgl.bar.update:
          id: power_bar_27
          value: !lambda return id(power_history)[27];
      - lvgl.bar.update:
          id: power_bar_28
          value: !lambda return id(power_history)[28];
      - lvgl.bar.update:
          id: power_bar_29
          value: !lambda return id(power_history)[29];

globals:
  - id: power_history
    type: float[30]
    restore_value: no
    initial_value: '{0}'

lvgl:
  pages:
    - id: meter_page
      widgets:
        - container:
            align: CENTER
            y: 200
            width: 220
            height: 40
            layout:
              type: FLEX
              flex_flow: ROW
              pad_row: 2
            widgets:
              - bar: &spark_bar
                  min_value: 0
                  max_value: 3000
                  width: 5
                  height: 40
                  bg_opa: 0
                  indicator:
                    bg_color: 0x607D8B

              - bar: { <<: *spark_bar, id: power_bar_0 }
              - bar: { <<: *spark_bar, id: power_bar_1 }
              - bar: { <<: *spark_bar, id: power_bar_2 }
              - bar: { <<: *spark_bar, id: power_bar_3 }
              - bar: { <<: *spark_bar, id: power_bar_4 }
              - bar: { <<: *spark_bar, id: power_bar_5 }
              - bar: { <<: *spark_bar, id: power_bar_6 }
              - bar: { <<: *spark_bar, id: power_bar_7 }
              - bar: { <<: *spark_bar, id: power_bar_8 }
              - bar: { <<: *spark_bar, id: power_bar_9 }
              - bar: { <<: *spark_bar, id: power_bar_10 }
              - bar: { <<: *spark_bar, id: power_bar_11 }
              - bar: { <<: *spark_bar, id: power_bar_12 }
              - bar: { <<: *spark_bar, id: power_bar_13 }
              - bar: { <<: *spark_bar, id: power_bar_14 }
              - bar: { <<: *spark_bar, id: power_bar_15 }
              - bar: { <<: *spark_bar, id: power_bar_16 }
              - bar: { <<: *spark_bar, id: power_bar_17 }
              - bar: { <<: *spark_bar, id: power_bar_18 }
              - bar: { <<: *spark_bar, id: power_bar_19 }
              - bar: { <<: *spark_bar, id: power_bar_20 }
              - bar: { <<: *spark_bar, id: power_bar_21 }
              - bar: { <<: *spark_bar, id: power_bar_22 }
              - bar: { <<: *spark_bar, id: power_bar_23 }
              - bar: { <<: *spark_bar, id: power_bar_24 }
              - bar: { <<: *spark_bar, id: power_bar_25 }
              - bar: { <<: *spark_bar, id: power_bar_26 }
              - bar: { <<: *spark_bar, id: power_bar_27 }
              - bar: { <<: *spark_bar, id: power_bar_28 }
              - bar: { <<: *spark_bar, id: power_bar_29 }