# ESPHome configuration for LilyGO T-Display S3 Pro
# Features: LVGL Chart (New YAML Syntax), SY6970 Power Management, Home Assistant Integration, Swipe Navigation

esphome:
  name: t-display-s3-pro-lvgltest
  friendly_name: "T-Display S3 Pro Power Monitor"
  platformio_options:
    build_flags: ["-DLV_USE_CHART=1"]
    board_build.flash_mode: dio
  on_boot:
    priority: 100
    then:
      - switch.turn_on: display_power
      - light.turn_on: { id: display_backlight, brightness: 100% }
      - script.execute: setup_chart

external_components:
  - source: github://pr#13987
    components: [lvgl]
    refresh: 1h

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

api:
  encryption:
    key: !secret api_secret

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

psram:
  mode: octal
  speed: 80MHz

logger:

debug:
  update_interval: 5s

spi:
  id: spi_bus
  clk_pin: 18
  mosi_pin: 17
  miso_pin: 16

i2c:
  id: i2c_bus
  sda: 5
  scl: 6

output:
  - platform: ledc
    pin: 48
    id: backlight_pwm
    frequency: 5000 Hz

light:
  - platform: monochromatic
    output: backlight_pwm
    id: display_backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 0s
    gamma_correct: 1.0

switch:
  - platform: gpio
    pin: 15
    id: display_power
    restore_mode: ALWAYS_ON

display:
  - platform: mipi_spi
    id: my_display
    model: t-display-s3-pro
    spi_id: spi_bus
    data_rate: 80MHz
    rotation: 90

touchscreen:
  - platform: cst226
    id: my_touch
    interrupt_pin: 21
    reset_pin: 13
    display: my_display

font:
  - file: 'fonts/GoogleSansCode-SemiBold.ttf'
    id: font_power
    size: 96
    bpp: 4
    glyphs: "0123456789.- W"
  - file: 'fonts/GoogleSansCode-SemiBold.ttf'
    id: font_axis
    size: 12
    bpp: 4
    glyphs: "12345kW"
  - file: 'fonts/GoogleSansCode-SemiBold.ttf'
    id: font_debug
    size: 14
    bpp: 4
    glyphs: "CPU0123456789% "

globals:
  - { id: battery_percent, type: float, initial_value: '0.0' }
  - { id: chart_obj, type: lv_obj_t*, initial_value: 'nullptr' }
  - { id: chart_main, type: lv_chart_series_t*, initial_value: 'nullptr' }
  - { id: chart_solar, type: lv_chart_series_t*, initial_value: 'nullptr' }
  - { id: last_main_power, type: float, initial_value: '0.0' }
  - { id: last_solar_power, type: float, initial_value: '0.0' }

lvgl:
  displays:
    - my_display
  touchscreens:
    - touchscreen_id: my_touch
  full_refresh: false
  buffer_size: 25%
  update_interval: 500ms
  # Corrected swipe triggers for page navigation
  on_swipe_left:
    then:
      - lvgl.page.show: page2
  on_swipe_right:
    then:
      - lvgl.page.show: page1
  pages:
    - id: page1
      bg_color: 0x000000
      widgets:
        - obj:
            width: 100%
            height: 34
            bg_color: 0x4A90FF
            align: TOP_MID
            widgets:
              - label: { id: time_p1, text: "--:--:--", text_font: montserrat_22, align: LEFT_MID, x: 10 }
              - label: { id: cpu_load_label, text: "CPU: --%", text_font: montserrat_22, align: LEFT_MID, x: 120 }
              - label: { id: batt_v_p1, text: "--.-V", text_font: montserrat_22, align: RIGHT_MID, x: -125 }
              - label: { id: batt_pct_p1, text: "--%", text_font: montserrat_22, align: RIGHT_MID, x: -55 }
              - label: { id: batt_icon_p1, text: "", text_font: montserrat_22, align: RIGHT_MID, x: -25 }
        - label:
            id: main_pwr_p1
            text: "---W"
            text_font: font_power
            align: TOP_RIGHT
            x: -10
            y: 20
        - obj:
            id: chart_container
            width: 185
            height: 194
            x: 0
            y: 39
            bg_color: 0x000000
            widgets:
              - { label: { text: "5kW", text_font: font_axis, x: 2, y: -8 } }
              - { label: { text: "1kW", text_font: font_axis, x: 2, y: 126 } }
        - label:
            id: solar_pwr_p1
            text: "---W"
            text_font: font_power
            align: TOP_RIGHT
            x: -10
            y: 110
            text_color: 0x2196F3

    - id: page2
      bg_color: 0x000000
      widgets:
        - label:
            text: "NEW YAML CHART COMPONENT"
            text_font: montserrat_14
            align: TOP_MID
            y: 5
        - chart:
            id: new_style_chart
            width: 90%
            height: 160
            align: BOTTOM_MID
            y: -10
            type: LINE
            point_count: 185
            update_mode: SHIFT
            range_y_min: 0
            range_y_max: 5000
            div_line_count_v: 11
            div_line_count_h: 0
            bg_color: 0x000000
            series:
              - id: series_main
                color: 0xF44336
              - id: series_solar
                color: 0x4CAF50
            styles:
              - part: INDICATOR
                size: 0
              - part: MAIN
                line_color: 0x303030
                line_opa: 60%

script:
  - id: setup_chart
    then:
      - lambda: |-
          if (id(chart_obj) == nullptr) {
            auto chart = lv_chart_create(id(chart_container));
            lv_obj_move_background(chart);
            id(chart_obj) = chart;
            lv_obj_set_size(chart, lv_pct(100), lv_pct(100));
            lv_obj_center(chart);
            lv_obj_set_style_pad_all(chart, 0, LV_PART_MAIN);
            lv_chart_set_type(chart, LV_CHART_TYPE_LINE);
            lv_chart_set_point_count(chart, 185);
            id(chart_main) = lv_chart_add_series(chart, lv_color_hex(0xF44336), LV_CHART_AXIS_PRIMARY_Y);
            id(chart_solar) = lv_chart_add_series(chart, lv_color_hex(0x4CAF50), LV_CHART_AXIS_PRIMARY_Y);
            lv_chart_set_range(chart, LV_CHART_AXIS_PRIMARY_Y, 0, 5000);
            lv_chart_set_update_mode(chart, LV_CHART_UPDATE_MODE_SHIFT);
            lv_obj_set_style_bg_color(chart, lv_color_hex(0x000000), LV_PART_MAIN);
            lv_obj_set_style_bg_opa(chart, LV_OPA_COVER, LV_PART_MAIN);
            lv_obj_set_style_size(chart, 0, LV_PART_INDICATOR);
            lv_obj_set_style_line_color(chart, lv_color_hex(0x303030), LV_PART_MAIN);
            lv_obj_set_style_line_opa(chart, LV_OPA_60, LV_PART_MAIN);
          }
  - id: update_battery_ui
    then:
      - lambda: |-
          float v = id(battery_voltage).state;   
          if (!isnan(v) && v > 2.0) {
            float pct = (v - 3.4f) / 0.8f * 100.0f;
            pct = std::clamp(pct, 0.0f, 100.0f);
            id(battery_percent) = pct;
            lv_label_set_text(id(batt_v_p1), str_sprintf("%.2fV", v).c_str());
            lv_label_set_text(id(batt_pct_p1), str_sprintf("%.0f%%", pct).c_str());
            const char* icon = (pct < 20) ? LV_SYMBOL_BATTERY_EMPTY : (pct < 80) ? LV_SYMBOL_BATTERY_2 : LV_SYMBOL_BATTERY_FULL;
            lv_label_set_text(id(batt_icon_p1), icon);
          }

sy6970:
  id: sy6970_hub
  i2c_id: i2c_bus
  update_interval: 1s

binary_sensor:
  - platform: gpio
    pin: { number: 14, mode: INPUT_PULLUP, inverted: true }
    on_state:
      then:
        - component.update: sy6970_hub
        - script.execute: update_battery_ui
  - platform: sy6970
    sy6970_id: sy6970_hub
    charging:
      id: charging_status
      on_state:
        then: [script.execute: update_battery_ui]
    vbus_connected:
      id: vbus_connected

interval:
  - interval: 1s
    then:
      - lambda: |-
          // Update Legacy Chart (Page 1)
          if (id(chart_obj) != nullptr) {
            lv_chart_set_next_value(id(chart_obj), id(chart_main), (lv_coord_t)id(last_main_power));
            lv_chart_set_next_value(id(chart_obj), id(chart_solar), (lv_coord_t)id(last_solar_power));
            lv_chart_refresh(id(chart_obj));
          }
          // Update New Component Chart (Page 2)
          id(new_style_chart).set_next_value(id(series_main), id(last_main_power));
          id(new_style_chart).set_next_value(id(series_solar), id(last_solar_power));

time:
  - platform: homeassistant
    id: esptime
    on_time:
      - seconds: /1
        then:
          - lvgl.label.update: { id: time_p1, text: !lambda 'return id(esptime).now().strftime("%H:%M:%S");' }

sensor:
  - platform: sy6970
    battery_voltage:
      id: battery_voltage
      on_value:
        then: [script.execute: update_battery_ui]
  - platform: homeassistant
    id: solar_power
    entity_id: sensor.dds238_2_solar_power
    on_value:
      - lvgl.label.update: { id: solar_pwr_p1, text: !lambda 'return str_sprintf("%.0fW", x);' }
      - lambda: 'id(last_solar_power) = x;'
  - platform: homeassistant
    id: main_power
    entity_id: sensor.ecotracker_current_power
    on_value:
      - lvgl.label.update: { id: main_pwr_p1, text: !lambda 'return str_sprintf("%.0fW", x);' }
      - lambda: |-
          lv_color_t c = (x < 0) ? lv_color_hex(0x2196F3) : (x <= 750) ? lv_color_hex(0x4CAF50) : lv_color_hex(0xF44336);
          lv_obj_set_style_text_color(id(main_pwr_p1), c, LV_PART_MAIN);
          id(last_main_power) = x;