esphome:
  name: t-display-s3-pro-lights

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

api:
  encryption:
    key: !secret api_secret

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

psram:
  mode: octal
  speed: 80MHz

logger:

power_supply:
  - id: backlight
    pin: 48
    enable_on_boot: true

spi:
  clk_pin: 18
  mosi_pin: 17

i2c:
  - scl: 6
    sda: 5
    scan: true
    id: i2c_onboard
    frequency: 400kHz

touchscreen:
  - platform: cst226
    interrupt_pin: 21
    reset_pin: 13
    on_touch:
      - lambda: |-
          ESP_LOGI(
            "cal",
            "x=%d, y=%d, x_raw=%d, y_raw=%0d",
            touch.x,
            touch.y,
            touch.x_raw,
            touch.y_raw
          );

display:
  - platform: mipi_spi
    model: t-display-s3-pro

######################################
# GLOBALS
######################################
globals:
  - id: slider_active
    type: bool
    restore_value: no
    initial_value: "false"

######################################
# SCRIPTS
######################################
script:
  # Debounce brightness updates sent to Home Assistant
  - id: debounce_light_slider
    mode: restart
    parameters:
      brightness_val: int
    then:
      - delay: 200ms
      - homeassistant.service:
          service: light.turn_on
          data:
            entity_id: light.yee_group
            brightness: !lambda return brightness_val;

  # Cool-down window after last touch/release
  - id: end_slider_touch
    mode: restart
    then:
      - delay: 1000ms
      - lambda: |-
          id(slider_active) = false;

######################################
# HOME ASSISTANT ENTITIES
######################################
binary_sensor:
  - platform: homeassistant
    id: yee_light_state
    entity_id: light.yee_group
    trigger_on_initial_state: true
    on_state:
      # Sync button state
      - lvgl.button.update:
          id: yee_light_btn
          state:
            checked: !lambda return x;

      # Light OFF → force slider to 0
      - if:
          condition:
            lambda: 'return !x;'
          then:
            - lvgl.slider.update:
                id: yee_slider
                value: 0

sensor:
  - platform: homeassistant
    id: yee_light_brightness
    entity_id: light.yee_group
    attribute: brightness
    on_value:
      # Only accept HA brightness when:
      # - light is ON
      # - slider is not in active or cooldown phase
      - if:
          condition:
            binary_sensor.is_on: yee_light_state
          then:
            - if:
                condition:
                  lambda: 'return !id(slider_active);'
                then:
                  - lvgl.slider.update:
                      id: yee_slider
                      value: !lambda return (int)x;

######################################
# LVGL UI
######################################
lvgl:
  pages:
    - id: lights_page
      bg_color: 0xF2F2EE
      widgets:

        ############################################
        # LIGHT CARD
        ############################################
        - container:
            width: 202
            height: 160
            x: 10
            y: 10
            pad_all: 10
            bg_color: 0xFFFFFF
            radius: 10

            widgets:

              ########################################
              # LIGHT BUTTON
              ########################################
              - button:
                  id: yee_light_btn
                  checkable: true
                  width: 180
                  height: 80
                  x: 1
                  y: 0
                  on_value:
                    - if:
                        condition:
                          lambda: 'return x;'
                        then:
                          - homeassistant.service:
                              service: light.turn_on
                              data:
                                entity_id: light.yee_group
                        else:
                          - homeassistant.service:
                              service: light.turn_off
                              data:
                                entity_id: light.yee_group
                  widgets:
                    - label:
                        text: "LR Lights"
                        text_font: montserrat_28
                        align: CENTER
                        text_color: 0x000000

              ########################################
              # BRIGHTNESS SLIDER
              ########################################
              - slider:
                  id: yee_slider
                  min_value: 0
                  max_value: 255
                  width: 180
                  x: 1
                  y: 100

                  on_press:
                    - script.stop: end_slider_touch
                    - lambda: |-
                        id(slider_active) = true;

                  on_value:
                    - script.execute:
                        id: debounce_light_slider
                        brightness_val: !lambda return (int)x;

                  on_release:
                    # Final sync with actual slider value
                    - script.execute:
                        id: debounce_light_slider
                        brightness_val: !lambda |-
                          return (int)lv_slider_get_value(id(yee_slider));
                    # Start cool-down window
                    - script.execute: end_slider_touch
