esphome:
  name: t-display-s3-pro-lightswitch

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

api:
  encryption:
    key: !secret api_secret

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

psram:
  mode: octal
  speed: 80MHz

logger:

power_supply:
  - id: backlight
    pin: 48
    enable_on_boot: true

spi:
  clk_pin: 18
  mosi_pin: 17

i2c:
  - scl: 6
    sda: 5
    scan: true
    id: i2c_onboard
    frequency: 400kHz

touchscreen:
  - platform: cst226
    interrupt_pin: 21
    reset_pin: 13
    on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.x, touch.y, touch.x_raw, touch.y_raw);

binary_sensor:
  - platform: cst226
    id: cst226_sensor
    on_click:
      - logger.log: Sensor clicked


display:
  - platform: mipi_spi
    model: t-display-s3-pro

####################################################
# LVGL USER INTERFACE
####################################################
lvgl:
  pages:
    - id: lights_page
      bg_color: 0xF2F2EE
      widgets:
        - container:
            width: 222
            height: 480
            pad_all: 10
            pad_row: 16
            scrollable: false
            layout:
              type: FLEX
              flex_flow: COLUMN

            widgets:

              ################################################
              # LIGHT 1
              ################################################
              - container:
                  width: 202
                  height: 90
                  pad_all: 8
                  bg_color: 0xFFFFFF
                  radius: 10
                  layout:
                    type: FLEX
                    flex_flow: COLUMN
                  widgets:
                    - switch:
                        text: "Living Room"
                        on_turn_on:
                          - homeassistant.service:
                              service: light.turn_on
                              data:
                                entity_id: light.yee_group
                        on_turn_off:
                          - homeassistant.service:
                              service: light.turn_off
                              data:
                                entity_id: light.living_room
                    - slider:
                        min_value: 1
                        max_value: 100
                        on_value:
                          - homeassistant.service:
                              service: light.turn_on
                              data:
                                entity_id: light.living_room
                                brightness_pct: !lambda return x;

              ################################################
              # LIGHT 2
              ################################################
              - container:
                  width: 202
                  height: 90
                  pad_all: 8
                  bg_color: 0xFFFFFF
                  radius: 10
                  layout:
                    type: FLEX
                    flex_flow: COLUMN
                  widgets:
                    - switch:
                        text: "Kitchen"
                        on_turn_on:
                          - homeassistant.service:
                              service: light.turn_on
                              data:
                                entity_id: light.yee_group
                        on_turn_off:
                          - homeassistant.service:
                              service: light.turn_off
                              data:
                                entity_id: light.yee_group
                    - slider:
                        min_value: 1
                        max_value: 100
                        on_value:
                          - homeassistant.service:
                              service: light.turn_on
                              data:
                                entity_id: light.kitchen
                                brightness_pct: !lambda return x;

              ################################################
              # LIGHT 3
              ################################################
              - container:
                  width: 202
                  height: 90
                  pad_all: 8
                  bg_color: 0xFFFFFF
                  radius: 10
                  layout:
                    type: FLEX
                    flex_flow: COLUMN
                  widgets:
                    - switch:
                        text: "Bedroom"
                        on_turn_on:
                          - homeassistant.service:
                              service: light.turn_on
                              data:
                                entity_id: light.yee_group
                        on_turn_off:
                          - homeassistant.service:
                              service: light.turn_off
                              data:
                                entity_id: light.yee_group
                    - slider:
                        min_value: 1
                        max_value: 100
                        on_value:
                          - homeassistant.service:
                              service: light.turn_on
                              data:
                                entity_id: light.bedroom
                                brightness_pct: !lambda return x;