esphome:
  name: t-display-s3-pro-lvgltest
  friendly_name: t-display-s3-pro-lvgltest
  platformio_options:
    build_flags: 
      - -DLV_USE_CHART=1
    build_unflags: -Werror=all
    board_build.flash_mode: dio
  on_boot:
    # Priority 100 is "Very Early" - essential for AMOLED power sequencing
    priority: 100 
    then:
      - switch.turn_on: display_power
      - light.turn_on:
          id: display_backlight
          brightness: 100%
      - delay: 500ms
      - script.execute: setup_chart

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf

# --- POWER & BACKLIGHT ---
output:
  - platform: ledc
    pin: 48
    id: backlight_pwm
    frequency: 5000 Hz

light:
  - platform: monochromatic
    output: backlight_pwm
    id: display_backlight
    restore_mode: ALWAYS_ON

switch:
  - platform: gpio
    pin: 15
    id: display_power
    restore_mode: ALWAYS_ON

# --- CONNECTIVITY ---
api:
  encryption:
    key: !secret api_secret
ota:
  - platform: esphome
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
  level: DEBUG

# --- HARDWARE ---
psram:
  mode: octal
  speed: 80MHz
spi:
  clk_pin: 18
  mosi_pin: 17
i2c:
  - scl: 6
    sda: 5
    id: i2c_onboard
    frequency: 100kHz

display:
  - platform: mipi_spi
    id: my_display
    model: t-display-s3-pro

touchscreen:
  - platform: cst226
    interrupt_pin: 21 
    reset_pin: 13

# --- ASSETS ---
font:
  - file: 'fonts/BebasNeue-Regular.ttf'
    id: font_bebas_160
    size: 160
  - file: 'fonts/BebasNeue-Regular.ttf'
    id: font_bebas_230
    size: 230
  - file: 'fonts/arial.ttf'
    id: font_arial_20
    size: 20

# --- GLOBALS ---
globals:
  - id: my_chart
    type: lv_obj_t*
    initial_value: 'nullptr'
  - id: ser_cons
    type: void*
    initial_value: 'nullptr'
  - id: ser_prod
    type: void*
    initial_value: 'nullptr'
  - id: ser_solar
    type: void*
    initial_value: 'nullptr'

# --- LVGL UI ---
lvgl:
  log_level: DEBUG
  pages:
    - id: page1
      bg_color: 0x000000
      on_focus:
        - lambda: 'if(id(my_chart)) lv_obj_add_flag(id(my_chart), LV_OBJ_FLAG_HIDDEN);'
      widgets:
        - obj: &header_bar
            width: 100%
            height: 30
            bg_color: 0x2828FF
            widgets:
              - label: { id: time_p1, text: "---", align: CENTER, text_font: font_arial_20 }
        - label:
            id: main_pwr_p1
            text: "--- W"
            text_font: font_bebas_230
            align: CENTER

    - id: page2
      bg_color: 0x000000
      on_focus:
        - lambda: 'if(id(my_chart)) lv_obj_clear_flag(id(my_chart), LV_OBJ_FLAG_HIDDEN);'
      widgets:
        - label:
            id: main_pwr_p2
            text: "--- W"
            text_font: font_bebas_160
            align: TOP_MID
            y: 35

    - id: page3
      bg_color: 0x000000
      on_focus:
        - lambda: 'if(id(my_chart)) lv_obj_clear_flag(id(my_chart), LV_OBJ_FLAG_HIDDEN);'
      widgets:
        - label:
            id: solar_pwr_p3
            text: "--- W"
            text_font: font_bebas_160
            align: TOP_MID
            y: 35

# --- SCRIPTS ---
script:
  - id: setup_chart
    then:
      - lambda: |-
          if (id(my_chart) == nullptr) {
            id(my_chart) = lv_chart_create(lv_scr_act());
            lv_obj_set_size(id(my_chart), 450, 120);
            lv_obj_align(id(my_chart), LV_ALIGN_BOTTOM_MID, 0, -10);
            lv_chart_set_type(id(my_chart), LV_CHART_TYPE_LINE);
            lv_chart_set_point_count(id(my_chart), 60);
            
            id(ser_cons) = (void*)lv_chart_add_series(id(my_chart), lv_color_hex(0xFF0000), LV_CHART_AXIS_PRIMARY_Y);
            id(ser_prod) = (void*)lv_chart_add_series(id(my_chart), lv_color_hex(0x00FF00), LV_CHART_AXIS_PRIMARY_Y);
            id(ser_solar) = (void*)lv_chart_add_series(id(my_chart), lv_color_hex(0xFF9900), LV_CHART_AXIS_PRIMARY_Y);
            
            lv_obj_add_flag(id(my_chart), LV_OBJ_FLAG_HIDDEN);
          }

# --- SENSORS ---
sensor:
  - platform: homeassistant
    id: dsmr_power_production
    entity_id: sensor.power_produced
    on_value:
      - lambda: 'if(id(my_chart)) lv_chart_set_next_value(id(my_chart), (lv_chart_series_t*)id(ser_prod), x * 1000.0);'

  - platform: homeassistant
    id: dsmr_power_consumption
    entity_id: sensor.power_consumed
    on_value:
      - lambda: 'if(id(my_chart)) lv_chart_set_next_value(id(my_chart), (lv_chart_series_t*)id(ser_cons), x * 1000.0);'

  - platform: homeassistant
    id: dsmr_total_power
    entity_id: sensor.ecotracker_current_power
    on_value:
      - lvgl.label.update: { id: main_pwr_p1, text: !lambda 'return str_sprintf("%.0f W", x);' }
      - lvgl.label.update: { id: main_pwr_p2, text: !lambda 'return str_sprintf("%.0f W", x);' }

  - platform: homeassistant
    id: solar_power
    entity_id: sensor.dds238_2_solar_energy_power
    on_value:
      - lvgl.label.update: { id: solar_pwr_p3, text: !lambda 'return str_sprintf("%.0f W", x);' }
      - lambda: 'if(id(my_chart)) lv_chart_set_next_value(id(my_chart), (lv_chart_series_t*)id(ser_solar), x);'

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO00
      inverted: true
      mode: INPUT_PULLUP
    id: button_next_page
    on_press:
      - lvgl.page.next:

time:
  - platform: homeassistant
    id: esptime