esphome:
  name: t-display-s3-pro-lights

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

api:
  encryption:
    key: !secret api_secret

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

psram:
  mode: octal
  speed: 80MHz

logger:

# --- BACKLIGHT CONTROL ---
output:
  - platform: ledc
    pin: 48
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    name: "Display Backlight"
    id: display_backlight
    restore_mode: ALWAYS_ON

# --- HARDWARE ---
spi:
  clk_pin: 18
  mosi_pin: 17

i2c:
  - scl: 6
    sda: 5
    scan: true
    id: i2c_onboard
    frequency: 400kHz

touchscreen:
  - platform: cst226
    interrupt_pin: 21
    reset_pin: 13
    on_touch:
      - light.turn_on: display_backlight
      - script.execute: screen_timeout

globals:
  - id: slider_active
    type: bool
    restore_value: no
    initial_value: "false"

# --- SCRIPTS ---
script:
  - id: debounce_light_slider
    mode: restart
    parameters:
      brightness_val: int
    then:
      - delay: 200ms
      - homeassistant.service:
          service: light.turn_on
          data:
            entity_id: light.yee_group
            brightness: !lambda return brightness_val;

  - id: screen_timeout
    mode: restart
    then:
      - delay: 30s
      - light.turn_off: display_backlight

  - id: end_slider_touch
    mode: restart
    then:
      - delay: 1000ms # Wait 1 second after the last touch/release
      - lambda: 'id(slider_active) = false;'

# --- HOME ASSISTANT SYNC ---
binary_sensor:
  - platform: homeassistant
    id: yee_light_state
    entity_id: light.yee_group
    trigger_on_initial_state: true
    on_state:
      - lvgl.button.update:
          id: yee_light_btn
          state:
            checked: !lambda return x;
      - if:
          condition:
            lambda: 'return !x;'
          then:
            - lvgl.slider.update:
                id: yee_slider
                value: 0
            - lvgl.label.update:
                id: yee_pct_label
                text: "0%"

sensor:
  - platform: homeassistant
    id: yee_light_brightness
    entity_id: light.yee_group
    attribute: brightness
    on_value:
      - if:
          condition:
            lambda: 'return !id(slider_active);'
          then:
            - lvgl.slider.update:
                id: yee_slider
                value: !lambda return (int)x;
            - lvgl.label.update:
                id: yee_pct_label
                text: !lambda |-
                  int pct = (int)((x / 255.0) * 100.0);
                  return to_string(pct) + "%";

display:
  - platform: mipi_spi
    model: t-display-s3-pro

# --- LVGL UI CONFIG ---
lvgl:
  # Removed 25% buffer as it causes issues in some versions. 
  # Using default which is safe for S3-Pro.
  full_refresh: false

  pages:
    - id: lights_page
      bg_color: 0xF2F2EE
      widgets:
        - container:
            width: 202
            height: 160
            x: 10
            y: 10
            pad_all: 10
            bg_color: 0xFFFFFF
            radius: 10
            widgets:
              - button:
                  id: yee_light_btn
                  checkable: true
                  width: 180
                  height: 80
                  x: 1
                  y: 0
                  bg_color: 0xDDDDDD # Default Off Color
                  on_value:
                    # STYLE UPDATE (The ESPHome Action way)
                    - if:
                        condition:
                          lambda: 'return x;'
                        then:
                          - lvgl.widget.update:
                              id: yee_light_btn
                              bg_color: 0x00FF00 # Green when ON
                          - homeassistant.service:
                              service: light.turn_on
                              data:
                                entity_id: light.yee_group
                        else:
                          - lvgl.widget.update:
                              id: yee_light_btn
                              bg_color: 0xDDDDDD # Gray when OFF
                          - homeassistant.service:
                              service: light.turn_off
                              data:
                                entity_id: light.yee_group
                  widgets:
                    - label:
                        text: "LR Lights"
                        text_font: montserrat_28
                        align: CENTER

              - label:
                  id: yee_pct_label
                  text: "0%"
                  text_font: montserrat_14
                  text_color: 0x808080
                  x: 155
                  y: 82

              - slider:
                  id: yee_slider
                  # ... (min/max/width/etc) ...
                  on_press:
                    - script.stop: end_slider_touch # Stop the cool-down if we touch again
                    - lambda: 'id(slider_active) = true;'
                  
                  on_value:
                    # Keep the label and debounce logic we already have
                    - lvgl.label.update:
                        id: yee_pct_label
                        text: !lambda |-
                          int pct = (int)((x / 255.0) * 100.0);
                          return to_string(pct) + "%";
                    - script.execute:
                        id: debounce_light_slider
                        brightness_val: !lambda return (int)x;

                  on_release:
                    # Final sync call
                    - script.execute:
                        id: debounce_light_slider
                        brightness_val: !lambda return (int)lv_slider_get_value(id(yee_slider));
                    # Start the cool-down timer
                    - script.execute: end_slider_touch