# Lilygo T-Display-S3-Pro
# To flash this to the device:
# With the device plugged in via USB:
#  - install ESPHome:
#       pip install esphome
#  - build and run:
#       esphome run t-display-s3-pro.yaml


esphome:
  name: t-display-s3-pro-energy

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

api:
  encryption:
    key: !secret api_secret

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

psram:
  mode: octal
  speed: 80MHz

logger:

power_supply:
  - id: backlight
    pin: 48
    enable_on_boot: true

spi:
  clk_pin: 18
  mosi_pin: 17

i2c:
  - scl: 6
    sda: 5
    scan: true
    id: i2c_onboard
    frequency: 400kHz

touchscreen:
  - platform: cst226
    interrupt_pin: 21
    reset_pin: 13
    on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.x, touch.y, touch.x_raw, touch.y_raw);

binary_sensor:
  - platform: cst226
    id: cst226_sensor
    on_click:
      - logger.log: Sensor clicked


display:
  - platform: mipi_spi
    model: t-display-s3-pro

sensor:
  - platform: homeassistant
    id: shellypro3em_total_power
    entity_id: sensor.441d6474d608_pro3em_active_power_c
    unit_of_measurement: 'W'
    on_value:
      - lambda: |-
          id(power_0)  = id(power_1);
          id(power_1)  = id(power_2);
          id(power_2)  = id(power_3);
          id(power_3)  = id(power_4);
          id(power_4)  = id(power_5);
          id(power_5)  = id(power_6);
          id(power_6)  = id(power_7);
          id(power_7)  = id(power_8);
          id(power_8)  = id(power_9);
          id(power_9)  = id(power_10);
          id(power_10) = id(power_11);
          id(power_11) = id(power_12);
          id(power_12) = id(power_13);
          id(power_13) = id(power_14);
          id(power_14) = id(power_15);
          id(power_15) = id(power_16);
          id(power_16) = id(power_17);
          id(power_17) = id(power_18);
          id(power_18) = id(power_19);
          id(power_19) = id(power_20);
          id(power_20) = id(power_21);
          id(power_21) = id(power_22);
          id(power_22) = id(power_23);
          id(power_23) = id(power_24);
          id(power_24) = id(power_25);
          id(power_25) = id(power_26);
          id(power_26) = id(power_27);
          id(power_27) = id(power_28);
          id(power_28) = id(power_29);

          float v = x;
          if (v < 0) v = 0;
          if (v > 3000) v = 3000;
          id(power_29) = v;


      - lvgl.bar.update:
          id: power_bar_0
          value: !lambda return id(power_0);
      - lvgl.bar.update:
          id: power_bar_1
          value: !lambda return id(power_1);
      - lvgl.bar.update:
          id: power_bar_2
          value: !lambda return id(power_2);
      - lvgl.bar.update:
          id: power_bar_3
          value: !lambda return id(power_3);
      - lvgl.bar.update:
          id: power_bar_4
          value: !lambda return id(power_4);
      - lvgl.bar.update:
          id: power_bar_5
          value: !lambda return id(power_5);
      - lvgl.bar.update:
          id: power_bar_6
          value: !lambda return id(power_6);
      - lvgl.bar.update:
          id: power_bar_7
          value: !lambda return id(power_7);
      - lvgl.bar.update:
          id: power_bar_8
          value: !lambda return id(power_8);
      - lvgl.bar.update:
          id: power_bar_9
          value: !lambda return id(power_9);
      - lvgl.bar.update:
          id: power_bar_10
          value: !lambda return id(power_10);
      - lvgl.bar.update:
          id: power_bar_11
          value: !lambda return id(power_11);
      - lvgl.bar.update:
          id: power_bar_12
          value: !lambda return id(power_12);
      - lvgl.bar.update:
          id: power_bar_13
          value: !lambda return id(power_13);
      - lvgl.bar.update:
          id: power_bar_14
          value: !lambda return id(power_14);
      - lvgl.bar.update:
          id: power_bar_15
          value: !lambda return id(power_15);
      - lvgl.bar.update:
          id: power_bar_16
          value: !lambda return id(power_16);
      - lvgl.bar.update:
          id: power_bar_17
          value: !lambda return id(power_17);
      - lvgl.bar.update:
          id: power_bar_18
          value: !lambda return id(power_18);
      - lvgl.bar.update:
          id: power_bar_19
          value: !lambda return id(power_19);
      - lvgl.bar.update:
          id: power_bar_20
          value: !lambda return id(power_20);
      - lvgl.bar.update:
          id: power_bar_21
          value: !lambda return id(power_21);
      - lvgl.bar.update:
          id: power_bar_22
          value: !lambda return id(power_22);
      - lvgl.bar.update:
          id: power_bar_23
          value: !lambda return id(power_23);
      - lvgl.bar.update:
          id: power_bar_24
          value: !lambda return id(power_24);
      - lvgl.bar.update:
          id: power_bar_25
          value: !lambda return id(power_25);
      - lvgl.bar.update:
          id: power_bar_26
          value: !lambda return id(power_26);
      - lvgl.bar.update:
          id: power_bar_27
          value: !lambda return id(power_27);
      - lvgl.bar.update:
          id: power_bar_28
          value: !lambda return id(power_28);
      - lvgl.bar.update:
          id: power_bar_29
          value: !lambda return id(power_29);


globals:
  - id: power_0
    type: float
    initial_value: '0'
  - id: power_1
    type: float
    initial_value: '0'
  - id: power_2
    type: float
    initial_value: '0'
  - id: power_3
    type: float
    initial_value: '0'
  - id: power_4
    type: float
    initial_value: '0'
  - id: power_5
    type: float
    initial_value: '0'
  - id: power_6
    type: float
    initial_value: '0'
  - id: power_7
    type: float
    initial_value: '0'
  - id: power_8
    type: float
    initial_value: '0'
  - id: power_9
    type: float
    initial_value: '0'
  - id: power_10
    type: float
    initial_value: '0'
  - id: power_11
    type: float
    initial_value: '0'
  - id: power_12
    type: float
    initial_value: '0'
  - id: power_13
    type: float
    initial_value: '0'
  - id: power_14
    type: float
    initial_value: '0'
  - id: power_15
    type: float
    initial_value: '0'
  - id: power_16
    type: float
    initial_value: '0'
  - id: power_17
    type: float
    initial_value: '0'
  - id: power_18
    type: float
    initial_value: '0'
  - id: power_19
    type: float
    initial_value: '0'
  - id: power_20
    type: float
    initial_value: '0'
  - id: power_21
    type: float
    initial_value: '0'
  - id: power_22
    type: float
    initial_value: '0'
  - id: power_23
    type: float
    initial_value: '0'
  - id: power_24
    type: float
    initial_value: '0'
  - id: power_25
    type: float
    initial_value: '0'
  - id: power_26
    type: float
    initial_value: '0'
  - id: power_27
    type: float
    initial_value: '0'
  - id: power_28
    type: float
    initial_value: '0'
  - id: power_29
    type: float
    initial_value: '0'


lvgl:
  pages:
    - id: meter_page
      widgets:
        - container:
            align: CENTER
            y: 200
            width: 220
            height: 40
            layout:
              type: FLEX
              flex_flow: ROW
              pad_row: 2
            widgets:
              - bar: &spark_bar
                  min_value: 0
                  max_value: 3000
                  width: 5
                  height: 40
                  bg_opa: 0
                  indicator:
                    bg_color: 0x607D8B

              - bar: { <<: *spark_bar, id: power_bar_0 }
              - bar: { <<: *spark_bar, id: power_bar_1 }
              - bar: { <<: *spark_bar, id: power_bar_2 }
              - bar: { <<: *spark_bar, id: power_bar_3 }
              - bar: { <<: *spark_bar, id: power_bar_4 }
              - bar: { <<: *spark_bar, id: power_bar_5 }
              - bar: { <<: *spark_bar, id: power_bar_6 }
              - bar: { <<: *spark_bar, id: power_bar_7 }
              - bar: { <<: *spark_bar, id: power_bar_8 }
              - bar: { <<: *spark_bar, id: power_bar_9 }
              - bar: { <<: *spark_bar, id: power_bar_10 }
              - bar: { <<: *spark_bar, id: power_bar_11 }
              - bar: { <<: *spark_bar, id: power_bar_12 }
              - bar: { <<: *spark_bar, id: power_bar_13 }
              - bar: { <<: *spark_bar, id: power_bar_14 }
              - bar: { <<: *spark_bar, id: power_bar_15 }
              - bar: { <<: *spark_bar, id: power_bar_16 }
              - bar: { <<: *spark_bar, id: power_bar_17 }
              - bar: { <<: *spark_bar, id: power_bar_18 }
              - bar: { <<: *spark_bar, id: power_bar_19 }
              - bar: { <<: *spark_bar, id: power_bar_20 }
              - bar: { <<: *spark_bar, id: power_bar_21 }
              - bar: { <<: *spark_bar, id: power_bar_22 }
              - bar: { <<: *spark_bar, id: power_bar_23 }
              - bar: { <<: *spark_bar, id: power_bar_24 }
              - bar: { <<: *spark_bar, id: power_bar_25 }
              - bar: { <<: *spark_bar, id: power_bar_26 }
              - bar: { <<: *spark_bar, id: power_bar_27 }
              - bar: { <<: *spark_bar, id: power_bar_28 }
              - bar: { <<: *spark_bar, id: power_bar_29 }