esphome:
  name: t-display-s3-pro-lights

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

api:
  encryption:
    key: !secret api_secret

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

psram:
  mode: octal
  speed: 80MHz

logger:

power_supply:
  - id: backlight
    pin: 48
    enable_on_boot: true

spi:
  clk_pin: 18
  mosi_pin: 17

i2c:
  - scl: 6
    sda: 5
    scan: true
    id: i2c_onboard
    frequency: 400kHz

touchscreen:
  - platform: cst226
    interrupt_pin: 21
    reset_pin: 13
    on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.x, touch.y, touch.x_raw, touch.y_raw);

binary_sensor:
  - platform: cst226
    id: cst226_sensor
    on_click:
      - logger.log: Sensor clicked

  - platform: homeassistant
    id: yee_light_state
    entity_id: light.yee_group
    on_state:
      - lvgl.button.update:
          id: yee_light_btn
          state:
            checked: !lambda return x;

sensor:
  - platform: homeassistant
    id: yee_light_brightness
    entity_id: light.yee_group
    attribute: brightness
    on_value:
      - if:
          condition:
            binary_sensor.is_on: yee_light_state
          then:
            - lvgl.slider.update:
                id: yee_slider
                value: !lambda return (int)x;
          else:
            - lvgl.slider.update:
                id: yee_slider
                value: 0



display:
  - platform: mipi_spi
    model: t-display-s3-pro

######################################
# LVGL UI
######################################
lvgl:
  pages:
    - id: lights_page
      bg_color: 0xF2F2EE
      widgets:

        # ===============================
        # PAGE CONTAINER
        # ===============================
        - container:
            width: 222
            height: 480
            pad_all: 3
            layout:
              type: FLEX
              flex_flow: COLUMN
              flex_align_main: START
              flex_align_cross: CENTER
              flex_align_track: START

            widgets:

              # ===============================
              # LIGHT CARD
              # ===============================
              - container:
                  width: 202
                  height: 160
                  pad_all: 10
                  bg_color: 0xFFFFFF
                  radius: 10
                  layout:
                    type: FLEX
                    flex_flow: COLUMN
                    flex_align_main: START
                    flex_align_cross: CENTER
                    flex_align_track: START

                  widgets:

                    ################################
                    # LIGHT BUTTON (light_btn)
                    ################################
                    - button:
                        id: yee_light_btn
                        checkable: true
                        width: 180
                        height: 40
                        on_value:
                          - if:
                              condition:
                                lambda: 'return x;'
                              then:
                                - homeassistant.service:
                                    service: light.turn_on
                                    data:
                                      entity_id: light.yee_group
                              else:
                                - homeassistant.service:
                                    service: light.turn_off
                                    data:
                                      entity_id: light.yee_group
                        widgets:
                          - label:
                              text: "Living Room"
                              align: CENTER
                              text_color: 0x000000

                    ################################
                    # SPACER (10 px)
                    ################################
                    - container:
                        height: 10
                        bg_opa: 0

                    ################################
                    # BRIGHTNESS SLIDER
                    ################################
                    - slider:
                        id: yee_slider
                        min_value: 0
                        max_value: 255
                        width: 180
                        on_release:
                          - homeassistant.service:
                              service: light.turn_on
                              data:
                                entity_id: light.yee_group
                                brightness: !lambda return (int)x;
