esphome:
  name: t-display-s3-pro-lights

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

api:
  encryption:
    key: !secret api_secret

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

psram:
  mode: octal
  speed: 80MHz

logger:

######################################
# BACKLIGHT (PWM DIMMABLE)
######################################
output:
  - platform: ledc
    pin: 48
    id: backlight_pwm
    frequency: 5000 Hz

light:
  - platform: monochromatic
    output: backlight_pwm
    id: display_backlight
    name: "Display Backlight"
    restore_mode: ALWAYS_ON
    default_transition_length: 0s

######################################
# SPI / I2C / DISPLAY
######################################
spi:
  clk_pin: 18
  mosi_pin: 17

i2c:
  - scl: 6
    sda: 5
    scan: true
    id: i2c_onboard
    frequency: 400kHz

display:
  - platform: mipi_spi
    model: t-display-s3-pro

######################################
# TOUCHSCREEN (WAKE BACKLIGHT)
######################################
touchscreen:
  - platform: cst226
    interrupt_pin: 21
    reset_pin: 13
    on_touch:
      - script.execute: backlight_wake

######################################
# GLOBALS
######################################
globals:
  - id: slider_active_lr
    type: bool
    restore_value: no
    initial_value: "false"

  - id: slider_active_hw
    type: bool
    restore_value: no
    initial_value: "false"

######################################
# SCRIPTS
######################################
script:
  # -------- BACKLIGHT --------
  - id: backlight_idle_timer
    mode: restart
    then:
      - delay: 30s
      - light.turn_on:
          id: display_backlight
          brightness: 30%

  - id: backlight_wake
    mode: restart
    then:
      - light.turn_on:
          id: display_backlight
          brightness: 100%
      - script.execute: backlight_idle_timer

  # -------- LIVING ROOM --------
  - id: debounce_lr
    mode: restart
    parameters:
      brightness_val: int
    then:
      - delay: 200ms
      - homeassistant.service:
          service: light.turn_on
          data:
            entity_id: light.yee_group
            brightness: !lambda return brightness_val;

  - id: end_slider_lr
    mode: restart
    then:
      - delay: 1000ms
      - lambda: 'id(slider_active_lr) = false;'

  # -------- HALLWAY --------
  - id: debounce_hw
    mode: restart
    parameters:
      brightness_val: int
    then:
      - delay: 200ms
      - homeassistant.service:
          service: light.turn_on
          data:
            entity_id: light.hallway_dimmer_light
            brightness: !lambda return brightness_val;

  - id: end_slider_hw
    mode: restart
    then:
      - delay: 1000ms
      - lambda: 'id(slider_active_hw) = false;'

######################################
# HOME ASSISTANT ENTITIES
######################################
binary_sensor:
  - platform: homeassistant
    id: lr_light_state
    entity_id: light.yee_group
    trigger_on_initial_state: true
    on_state:
      - lvgl.button.update:
          id: lr_btn
          state:
            checked: !lambda return x;
      - if:
          condition:
            lambda: 'return !x;'
          then:
            - lvgl.slider.update:
                id: lr_slider
                value: 0
            - lvgl.label.update:
                id: lr_pct
                text: "0%"

  - platform: homeassistant
    id: hw_light_state
    entity_id: light.hallway_dimmer_light
    trigger_on_initial_state: true
    on_state:
      - lvgl.button.update:
          id: hw_btn
          state:
            checked: !lambda return x;
      - if:
          condition:
            lambda: 'return !x;'
          then:
            - lvgl.slider.update:
                id: hw_slider
                value: 0
            - lvgl.label.update:
                id: hw_pct
                text: "0%"

sensor:
  - platform: homeassistant
    id: lr_brightness
    entity_id: light.yee_group
    attribute: brightness
    on_value:
      - if:
          condition:
            lambda: |-
              return !isnan(x) &&
                     id(lr_light_state).state &&
                     !id(slider_active_lr);
          then:
            - lvgl.slider.update:
                id: lr_slider
                value: !lambda return (int)x;
            - lvgl.label.update:
                id: lr_pct
                text: !lambda |-
                  int pct = (int)((x / 255.0) * 100.0);
                  return to_string(pct) + "%";

  - platform: homeassistant
    id: hw_brightness
    entity_id: light.hallway_dimmer_light
    attribute: brightness
    on_value:
      - if:
          condition:
            lambda: |-
              return !isnan(x) &&
                     id(hw_light_state).state &&
                     !id(slider_active_hw);
          then:
            - lvgl.slider.update:
                id: hw_slider
                value: !lambda return (int)x;
            - lvgl.label.update:
                id: hw_pct
                text: !lambda |-
                  int pct = (int)((x / 255.0) * 100.0);
                  return to_string(pct) + "%";

######################################
# LVGL UI
######################################
lvgl:
  pages:
    - id: lights_page
      bg_color: 0xF2F2EE
      widgets:

        # ---------- LIVING ROOM ----------
        - container:
            width: 202
            height: 160
            x: 10
            y: 10
            pad_all: 10
            bg_color: 0xFFFFFF
            radius: 10
            widgets:

              - button:
                  id: lr_btn
                  checkable: true
                  width: 180
                  height: 70
                  x: 1
                  y: 0
                  on_value:
                    - if:
                        condition:
                          lambda: 'return x;'
                        then:
                          - homeassistant.service:
                              service: light.turn_on
                              data:
                                entity_id: light.yee_group
                        else:
                          - homeassistant.service:
                              service: light.turn_off
                              data:
                                entity_id: light.yee_group
                  widgets:
                    - label:
                        text: "Living Room"
                        align: CENTER

              - label:
                  id: lr_pct
                  text: "0%"
                  text_font: montserrat_14
                  text_color: 0x808080
                  x: 155
                  y: 82

              - slider:
                  id: lr_slider
                  min_value: 0
                  max_value: 255
                  width: 180
                  x: 1
                  y: 100
                  on_press:
                    - script.stop: end_slider_lr
                    - lambda: 'id(slider_active_lr) = true;'
                  on_value:
                    - lvgl.label.update:
                        id: lr_pct
                        text: !lambda |-
                          int pct = (int)((x / 255.0) * 100.0);
                          return to_string(pct) + "%";
                    - if:
                        condition:
                          binary_sensor.is_on: lr_light_state
                        then:
                          - script.execute:
                              id: debounce_lr
                              brightness_val: !lambda return (int)x;
                  on_release:
                    - script.execute:
                        id: debounce_lr
                        brightness_val: !lambda return (int)lv_slider_get_value(id(lr_slider));
                    - script.execute: end_slider_lr

        # ---------- HALLWAY ----------
        - container:
            width: 202
            height: 160
            x: 10
            y: 190
            pad_all: 10
            bg_color: 0xFFFFFF
            radius: 10
            widgets:

              - button:
                  id: hw_btn
                  checkable: true
                  width: 180
                  height: 70
                  x: 1
                  y: 0
                  on_value:
                    - if:
                        condition:
                          lambda: 'return x;'
                        then:
                          - homeassistant.service:
                              service: light.turn_on
                              data:
                                entity_id: light.hallway_dimmer_light
                        else:
                          - homeassistant.service:
                              service: light.turn_off
                              data:
                                entity_id: light.hallway_dimmer_light
                  widgets:
                    - label:
                        text: "Hallway"
                        align: CENTER

              - label:
                  id: hw_pct
                  text: "0%"
                  text_font: montserrat_14
                  text_color: 0x808080
                  x: 155
                  y: 82

              - slider:
                  id: hw_slider
                  min_value: 0
                  max_value: 255
                  width: 180
                  x: 1
                  y: 100
                  on_press:
                    - script.stop: end_slider_hw
                    - lambda: 'id(slider_active_hw) = true;'
                  on_value:
                    - lvgl.label.update:
                        id: hw_pct
                        text: !lambda |-
                          int pct = (int)((x / 255.0) * 100.0);
                          return to_string(pct) + "%";
                    - if:
                        condition:
                          binary_sensor.is_on: hw_light_state
                        then:
                          - script.execute:
                              id: debounce_hw
                              brightness_val: !lambda return (int)x;
                  on_release:
                    - script.execute:
                        id: debounce_hw
                        brightness_val: !lambda return (int)lv_slider_get_value(id(hw_slider));
                    - script.execute: end_slider_hw
