esphome:
  name: t-display-s3-pro-lvgltest
  friendly_name: "T-Display S3 Pro Power Monitor"
  platformio_options:
    build_flags: ["-DLV_USE_CHART=1"]
    board_build.flash_mode: dio
  on_boot:
    priority: 100
    then:
      - switch.turn_on: display_power
      - light.turn_on: { id: display_backlight, brightness: 100% }

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

external_components:
  - source: github://esphome/esphome@dev
    components: [sy6970]

api:
  encryption:
    key: !secret api_secret

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

psram:
  mode: octal
  speed: 80MHz

logger:

spi:
  clk_pin: 18
  mosi_pin: 17
  miso_pin: 16

i2c:
  id: i2c_bus
  sda: 5
  scl: 6

output:
  - platform: ledc
    pin: 48
    id: backlight_pwm

light:
  - platform: monochromatic
    output: backlight_pwm
    id: display_backlight

switch:
  - platform: gpio
    pin: 15
    id: display_power
    restore_mode: ALWAYS_ON

display:
  - platform: mipi_spi
    id: my_display
    model: t-display-s3-pro
    rotation: 90

touchscreen:
  - platform: cst226
    id: my_touch
    interrupt_pin: 21
    reset_pin: 13
    display: my_display

font:
  - file: 'fonts/Oswald-Bold.ttf'
    id: font_power
    size: 96
    bpp: 4
    glyphs: "0123456789.- W"

globals:
  - { id: battery_percent, type: float, initial_value: '0.0' }

lvgl:
  displays:
    - my_display
  touchscreens:
    - touchscreen_id: my_touch
  buffer_size: 25%
  pages:
    - id: page1
      bg_color: 0x000000
      widgets:
        - obj:
            width: 100%
            height: 34
            bg_color: 0x4A90FF
            align: TOP_MID
            widgets:
              - label:
                  id: time_p1
                  text: "--:--:--"
                  text_font: montserrat_22
                  align: LEFT_MID
                  x: 10
              - label:
                  id: batt_v_p1
                  text: "--.-V"
                  text_font: montserrat_22
                  align: RIGHT_MID
                  x: -110
              - label:
                  id: batt_pct_p1
                  text: "--%"
                  text_font: montserrat_22
                  align: RIGHT_MID
                  x: -40
              - label:
                  id: batt_icon_p1
                  text: ""
                  text_font: montserrat_22
                  align: RIGHT_MID
                  x: -10
        - obj:
            width: 100%
            height: 180
            align: TOP_MID
            y: 34
            layout: { type: FLEX, flex_flow: COLUMN, flex_align_main: CENTER, flex_align_cross: CENTER }
            bg_opa: 0
            widgets:
              - label:
                  id: main_pwr_p1
                  text: "--- W"
                  text_font: font_power
                  width: 100%
                  align: CENTER
                  text_align: CENTER

sy6970:
  i2c_id: i2c_bus
  update_interval: 30s

time:
  - platform: homeassistant
    id: esptime
    on_time:
      - seconds: /1
        then:
          - lvgl.label.update: { id: time_p1, text: !lambda 'return id(esptime).now().strftime("%H:%M:%S");' }

sensor:
  - platform: sy6970
    battery_voltage:
      id: battery_voltage
      on_value:
        - lambda: |-
            float pct = (x - 3.0f) / 1.2f * 100.0f;
            if (pct < 0) pct = 0;
            if (pct > 100) pct = 100;
            id(battery_percent) = pct;
        - lambda: |-
            const char* icon;
            if (id(battery_percent) < 20) icon = LV_SYMBOL_BATTERY_EMPTY;
            else if (id(battery_percent) < 40) icon = LV_SYMBOL_BATTERY_1;
            else if (id(battery_percent) < 60) icon = LV_SYMBOL_BATTERY_2;
            else if (id(battery_percent) < 80) icon = LV_SYMBOL_BATTERY_3;
            else icon = LV_SYMBOL_BATTERY_FULL;
            lv_label_set_text(id(batt_icon_p1), icon);
        - lvgl.label.update: { id: batt_v_p1, text: !lambda 'return str_sprintf("%.2fV", x);' }
        - lvgl.label.update: { id: batt_pct_p1, text: !lambda 'return str_sprintf("%.0f%%", id(battery_percent));' }

  - platform: homeassistant
    id: main_power
    entity_id: sensor.ecotracker_current_power
    on_value:
      - if:
          condition: { lambda: 'return !isnan(x);' }
          then:
            - lvgl.label.update: { id: main_pwr_p1, text: !lambda 'return str_sprintf("%.0f W", x);' }
            - lambda: |-
                // Smooth gradient color
                lv_color_t c;
                if (x < 0) {
                  // Export power = blue gradient (0 to -2000W)
                  float t = fminf(fabsf(x) / 2000.0f, 1.0f);
                  uint8_t r = (uint8_t)(79  * (1.0f - t));
                  uint8_t g = (uint8_t)(195 * (1.0f - t));
                  uint8_t b = 247;
                  c = lv_color_make(r, g, b);
                } else {
                  // Import power gradient: Green -> Orange -> Red (0–3600W)
                  float t = fminf(x / 3600.0f, 1.0f);
                  uint8_t r = (uint8_t)(76  + (244 - 76)  * t);
                  uint8_t g = (uint8_t)(175 - (175 - 67) * t);
                  uint8_t b = (uint8_t)(80  - 80 * t);
                  c = lv_color_make(r, g, b);
                }
                lv_obj_set_style_text_color(id(main_pwr_p1), c, LV_PART_MAIN);