# ESPHome configuration for LilyGO T-Display S3 Pro
# Features: LVGL Chart, SY6970 Power Management, Home Assistant Integration

esphome:
  name: t-display-s3-pro-power-monitor
  friendly_name: "T-Display S3 Pro Power Monitor"
  platformio_options:
    build_flags: ["-DLV_USE_CHART=1"]
    board_build.flash_mode: dio
  on_boot:
    priority: 100
    then:
      - switch.turn_on: display_power
      - light.turn_on: { id: display_backlight, brightness: 100% }
      - script.execute: setup_chart

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

external_components:
  - source: github://esphome/esphome@dev
    components: [sy6970]

api:
  encryption:
    key: !secret api_secret

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

psram:
  mode: octal
  speed: 80MHz

logger:

spi:
  id: spi_bus
  clk_pin: 18
  mosi_pin: 17
  miso_pin: 16

i2c:
  id: i2c_bus
  sda: 5
  scl: 6

output:
  - platform: ledc
    pin: 48
    id: backlight_pwm
    frequency: 5000 Hz

light:
  - platform: monochromatic
    output: backlight_pwm
    id: display_backlight
    restore_mode: ALWAYS_ON
    default_transition_length: 0s
    gamma_correct: 1.0

switch:
  - platform: gpio
    pin: 15
    id: display_power
    restore_mode: ALWAYS_ON

display:
  - platform: mipi_spi
    id: my_display
    model: t-display-s3-pro
    spi_id: spi_bus
    data_rate: 80MHz
    rotation: 90

touchscreen:
  - platform: cst226
    id: my_touch
    interrupt_pin: 21
    reset_pin: 13
    display: my_display

font:
  - file: 'fonts/GoogleSansCode-SemiBold.ttf'
    id: font_power
    size: 96
    bpp: 4
    glyphs: "0123456789.- W"
  - file: 'fonts/GoogleSansCode-SemiBold.ttf'
    id: font_axis
    size: 12
    bpp: 4
    glyphs: "12345kW"

globals:
  - { id: battery_percent, type: float, initial_value: '0.0' }
  - { id: chart_obj, type: lv_obj_t*, initial_value: 'nullptr' }
  - { id: chart_main, type: lv_chart_series_t*, initial_value: 'nullptr' }
  - { id: chart_solar, type: lv_chart_series_t*, initial_value: 'nullptr' }
  - { id: last_main_power, type: float, initial_value: '0.0' }
  - { id: last_solar_power, type: float, initial_value: '0.0' }

lvgl:
  displays:
    - my_display
  touchscreens:
    - touchscreen_id: my_touch
  full_refresh: false
  buffer_size: 25%
  update_interval: 500ms
  pages:
    - id: page1
      bg_color: 0x000000
      scrollable: false
      widgets:
        - obj:
            width: 100%
            height: 34
            bg_color: 0x4A90FF
            border_width: 0
            outline_width: 0
            align: TOP_MID
            widgets:
              - label:
                  id: time_p1
                  text: "--:--:--"
                  text_font: montserrat_22
                  align: LEFT_MID
                  x: 10
              - label:
                  id: batt_v_p1
                  text: "--.-V"
                  text_font: montserrat_22
                  align: RIGHT_MID
                  x: -110
              - label:
                  id: batt_pct_p1
                  text: "--%"
                  text_font: montserrat_22
                  align: RIGHT_MID
                  x: -40
              - label:
                  id: batt_icon_p1
                  text: ""
                  text_font: montserrat_22
                  align: RIGHT_MID
                  x: -10
        - label:
            id: main_pwr_p1
            text: "---W"
            text_font: font_power
            align: TOP_RIGHT
            x: -10
            y: 20
            text_align: RIGHT
        - obj:
            id: chart_container
            width: 185
            height: 194
            x: 0
            y: 39
            bg_color: 0x000000
            bg_opa: COVER
            border_width: 0
            outline_width: 0
            widgets:
              - { label: { text: "5kW", text_font: font_axis, text_color: 0xFFFFFF, x: 2, y: -8 } }
              - { label: { text: "4kW", text_font: font_axis, text_color: 0xFFFFFF, x: 2, y: 24 } }
              - { label: { text: "3kW", text_font: font_axis, text_color: 0xFFFFFF, x: 2, y: 58 } }
              - { label: { text: "2kW", text_font: font_axis, text_color: 0xFFFFFF, x: 2, y: 92 } }
              - { label: { text: "1kW", text_font: font_axis, text_color: 0xFFFFFF, x: 2, y: 126 } }
        - label:
            id: solar_pwr_p1
            text: "---W"
            text_font: font_power
            align: TOP_RIGHT
            x: -10
            y: 110
            text_align: RIGHT
            text_color: 0x2196F3

script:
  - id: setup_chart
    then:
      - lambda: |-
          if (id(chart_obj) == nullptr) {
            auto chart = lv_chart_create(id(chart_container));
            lv_obj_move_background(chart);
            id(chart_obj) = chart;
            lv_obj_set_size(chart, lv_pct(100), lv_pct(100));
            lv_obj_center(chart);
            lv_obj_set_style_pad_all(chart, 0, LV_PART_MAIN);
            lv_chart_set_type(chart, LV_CHART_TYPE_LINE);
            lv_chart_set_point_count(chart, 185);
            id(chart_main) = lv_chart_add_series(chart, lv_color_hex(0xF44336), LV_CHART_AXIS_PRIMARY_Y);
            id(chart_solar) = lv_chart_add_series(chart, lv_color_hex(0x4CAF50), LV_CHART_AXIS_PRIMARY_Y);
            lv_chart_set_range(chart, LV_CHART_AXIS_PRIMARY_Y, 0, 5000);
            lv_chart_set_update_mode(chart, LV_CHART_UPDATE_MODE_SHIFT);
            lv_obj_set_style_bg_color(chart, lv_color_hex(0x000000), LV_PART_MAIN);
            lv_obj_set_style_bg_opa(chart, LV_OPA_COVER, LV_PART_MAIN);
            lv_obj_set_style_border_width(chart, 0, LV_PART_MAIN);
            lv_obj_set_style_outline_width(chart, 0, LV_PART_MAIN);
            lv_obj_clear_flag(chart, LV_OBJ_FLAG_SCROLLABLE);
            lv_chart_set_div_line_count(chart, 11, 0);
            lv_obj_set_style_size(chart, 0, LV_PART_INDICATOR);
            lv_obj_set_style_line_color(chart, lv_color_hex(0x303030), LV_PART_MAIN);
            lv_obj_set_style_line_opa(chart, LV_OPA_60, LV_PART_MAIN);
          }
  - id: update_battery_ui
    then:
      - lambda: |-
          float v = id(battery_voltage).state;
          bool is_usb = (id(usb_voltage).state > 4.2f);
          
          if (!isnan(v) && v > 2.0) {
            float pct = (v - 3.4f) / 0.8f * 100.0f;
            if (pct < 0) pct = 0;
            if (pct > 100) pct = 100;
            id(battery_percent) = pct;
            
            lv_label_set_text(id(batt_v_p1), str_sprintf("%.2fV", v).c_str());
            lv_label_set_text(id(batt_pct_p1), str_sprintf("%.0f%%", pct).c_str());
            
            const char* icon;
            if (is_usb) {
              icon = "⚡"; 
            } else {
              if (pct < 20) icon = LV_SYMBOL_BATTERY_EMPTY;
              else if (pct < 40) icon = LV_SYMBOL_BATTERY_1;
              else if (pct < 60) icon = LV_SYMBOL_BATTERY_2;
              else if (pct < 80) icon = LV_SYMBOL_BATTERY_3;
              else icon = LV_SYMBOL_BATTERY_FULL;
            }
            lv_label_set_text(id(batt_icon_p1), icon);
          }

sy6970:
  i2c_id: i2c_bus
  update_interval: 5s

binary_sensor:
  - platform: template
    id: usb_present
    lambda: |-
      return id(usb_voltage).state > 4.2;

interval:
  - interval: 1s
    then:
      - lambda: |-
          if (id(chart_obj) != nullptr) {
            lv_chart_set_next_value(id(chart_obj), id(chart_main), (lv_coord_t)id(last_main_power));
            lv_chart_set_next_value(id(chart_obj), id(chart_solar), (lv_coord_t)id(last_solar_power));
            lv_chart_refresh(id(chart_obj));
          }
  - interval: 5s
    then:
      - script.execute: update_battery_ui

time:
  - platform: homeassistant
    id: esptime
    on_time:
      - seconds: /1
        then:
          - lvgl.label.update: { id: time_p1, text: !lambda 'return id(esptime).now().strftime("%H:%M:%S");' }

sensor:
  - platform: sy6970
    vbus_voltage:
      id: usb_voltage
      on_value:
        then:
          - script.execute: update_battery_ui
    battery_voltage:
      id: battery_voltage
      on_value:
        then:
          - script.execute: update_battery_ui

  - platform: homeassistant
    id: solar_power
    entity_id: sensor.dds238_2_solar_power
    filters:
      - throttle: 1s
    on_value:
      - if:
          condition: { lambda: 'return !isnan(x);' }
          then:
            - lvgl.label.update: { id: solar_pwr_p1, text: !lambda 'return str_sprintf("%.0fW", x);' }
            - lambda: |-
                id(last_solar_power) = x;

  - platform: homeassistant
    id: main_power
    entity_id: sensor.ecotracker_current_power
    filters:
      - throttle: 1s
    on_value:
      - if:
          condition: { lambda: 'return !isnan(x);' }
          then:
            - lvgl.label.update: { id: main_pwr_p1, text: !lambda 'return str_sprintf("%.0fW", x);' }
            - lambda: |-
                lv_color_t c;
                if (x < 0) c = lv_color_hex(0x2196F3);
                else if (x <= 750) c = lv_color_hex(0x4CAF50);
                else if (x <= 1000) c = lv_color_hex(0xFF803B);
                else if (x <= 2000) c = lv_color_hex(0xFF9800);
                else c = lv_color_hex(0xF44336);
                lv_obj_set_style_text_color(id(main_pwr_p1), c, LV_PART_MAIN);
                id(last_main_power) = x;