esphome:
  name: tdisplay-s3-lvgltesting
  friendly_name: tdisplay-s3-lvgltesting

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

spi:
  id: quad_spi
  type: quad
  clk_pin: 47
  data_pins:
    - 18
    - 7
    - 48
    - 5

# Enable logging
logger:

api:
  encryption:
    key: !secret api_secret

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

display:
  - platform: qspi_dbi
    auto_clear_enabled: false
    id: my_display
    model: RM67162
    dimensions:
      height: 240
      width: 536
      offset_height: 0
      offset_width: 0
    transform:
      mirror_x: true
      mirror_y: false
      swap_xy: true
    color_order: rgb
    invert_colors: false
    brightness: 175
    cs_pin: 6
    reset_pin: 17
    enable_pin: 38

# lvgl:
#   widgets:
#     - label:
#         align: CENTER
#         text: 'Hello World!'

# Sensor configuration
# sensor:
#   - platform: homeassistant
#     id: sensor_dsmr_total_sg_mqtt
#     entity_id: sensor.dsmr_total_sg_mqtt
#     internal: true
#     on_value:
#       then:
#       - lvgl.indicator.update:
#           id: power_needle
#           value: !lambda return x * 10;
#       - lvgl.label.update:
#           id: power_text
#           text:
#             format: "%.1fW"
#             args: [ 'x' ]