# Lilygo T-Display-S3-Pro
# To flash this to the device:
# With the device plugged in via USB:
#  - install ESPHome:
#       pip install esphome
#  - build and run:
#       esphome run t-display-s3-pro.yaml


esphome:
  name: t-display-s3-pro

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

api:
  encryption:
    key: !secret api_secret

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

psram:
  mode: octal
  speed: 80MHz

logger:

power_supply:
  - id: backlight
    pin: 48
    enable_on_boot: true

spi:
  clk_pin: 18
  mosi_pin: 17

i2c:
  - scl: 6
    sda: 5
    scan: true
    id: i2c_onboard
    frequency: 400kHz

touchscreen:
  - platform: cst226
    interrupt_pin: 21
    reset_pin: 13
    on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.x, touch.y, touch.x_raw, touch.y_raw);

binary_sensor:
  - platform: cst226
    id: cst226_sensor
    on_click:
      - logger.log: Sensor clicked


display:
  - platform: mipi_spi
    model: t-display-s3-pro

sensor:
  - platform: homeassistant
    id: outdoor_temperature
    entity_id: sensor.atc_9c3e_temperature
    on_value:
      - lvgl.indicator.update:
          id: outdoor_temperature_needle
          value: !lambda return x * 10;

      - lvgl.label.update:
          id: outdoor_temperature_text
          text: !lambda |-
            if (isnan(x)) {
              return std::string("-.-°C");
            }
            char buf[16];
            snprintf(buf, sizeof(buf), "%.1f°C", x);
            return std::string(buf);

  - platform: homeassistant
    id: indoor_temperature
    entity_id: sensor.atc_8153_temperature   # <-- adjust to your HA entity
    on_value:
      - lvgl.indicator.update:
          id: indoor_temperature_needle
          value: !lambda return x * 10;

      - lvgl.label.update:
          id: indoor_temperature_text
          text: !lambda |-
            if (isnan(x)) return std::string("-.-°C");
            char buf[16];
            snprintf(buf, sizeof(buf), "%.1f°C", x);
            return std::string(buf);

lvgl:
  pages:
    - id: meter_page
      bg_color: 0xDDDDDD  
      widgets:

        # ===== INDOOR (TOP) =====
        - meter:
            id: indoor_meter
            align: CENTER
            y: -100
            height: 180
            width: 180
            bg_opa: 0
            scales:
              - range_from: 0
                range_to: 400
                angle_range: 240
                rotation: 150
                indicators:
                  - line:
                      id: indoor_temperature_needle
                      width: 3
                      color: 0x3bb606  # muted green
                      r_mod: -4
                  - tick_style:
                      start_value: 0
                      end_value: 40
                      color_start: 0x0000bd
                      color_end: 0xbd0000
                      width: 1
              - range_from: 0
                range_to: 40
                angle_range: 240
                rotation: 150
                ticks:
                  width: 1
                  count: 51
                  length: 8
                  color: 0xB0B0B0     # minor ticks
                  major:
                    stride: 5
                    width: 2
                    length: 12
                    color: 0x707070   # major ticks + numbers
                    label_gap: 10
            widgets:
              - label:
                  id: indoor_temperature_text
                  text: "-.-°C"
                  align: CENTER
                  y: 45
                  text_color: 0x1A1A1A
              - label:
                  text: "Indoor"
                  align: CENTER
                  y: 65
                  text_color: 0x404040

        # ===== OUTDOOR (BOTTOM) =====
        - meter:
            align: CENTER
            y: 100
            height: 180
            width: 180
            bg_opa: 0
            scales:
              - range_from: -200
                range_to: 400
                angle_range: 240
                rotation: 150
                indicators:
                  - line:
                      id: outdoor_temperature_needle
                      width: 3
                      color: 0x3C9FF9 #blue
                      r_mod: -4
                  - tick_style:
                      start_value: -20
                      end_value: 40
                      color_start: 0x0000bd
                      color_end: 0xbd0000
                      width: 1
              - range_from: -20
                range_to: 40
                angle_range: 240
                rotation: 150
                ticks:
                  width: 1
                  count: 61
                  length: 8
                  color: 0xB0B0B0
                  major:
                    stride: 5
                    width: 2
                    length: 12
                    color: 0x707070
                    label_gap: 10
            widgets:
              - label:
                  id: outdoor_temperature_text
                  text: "-.-°C"
                  align: CENTER
                  y: 45
                  text_color: 0x1A1A1A
              - label:
                  text: "Outdoor"
                  align: CENTER
                  y: 65
                  text_color: 0x404040
