esphome:
  name: ttgo-tdisplay-aj-sr04m
  friendly_name: ttgo-tdisplay-aj-sr04m

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_secret

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

uart:
  tx_pin: GPIO2
  rx_pin: GPIO15
  baud_rate: 9600

sensor:
  - platform: "jsn_sr04t"
    name: "Distance"
    update_interval: 1s